### ISSUE TITLE
omxp_spawn.js:8 problem with execSync

### ISSUE THREAD

**Issue by JoshSK** [winstonwp/omxplayer-controll#5]
Hello I have problem with you library

```
testing/node_modules/omxplayer-controll/lib/omxp_spawn.js:8
    var stdout = execSync('ps xa | grep "[o]mxplayer.bin" | wc -l');
                 ^
TypeError: undefined is not a function
    at omxp_running (/testing/node_modules/omxplayer-controll/lib/omxp_spawn.js:8:18)
    at EventEmitter.module.exports.player (testing/node_modules/omxplayer-controll/lib/omxp_spawn.js:14:17)
    at EventEmitter.openPlayer [as open] (testing/node_modules/omxplayer-controll/lib/omxp_dbus.js:14:16)
```
node version is
v0.10.29

npm version
4.0.5

OS:
"Raspbian GNU/Linux 8 (jessie)"

Can you help me please?

thx

**Comment by sport4minus** [comment]
you need to update node.js to v0.12
see [here](https://strongloop.com/strongblog/whats-new-in-node-js-v0-12-execsync-a-synchronous-api-for-child-processes/)

**Comment by JoshSK** [comment]
Great, now its working
thanks so much
